version: '3'

services:
  master:
    image: locustio/locust
    ports:
     - "60000:8089"
    volumes:
      - ./log:/locust/log
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile2.py --master -H http://master:8089  --headless --csv=/mnt/locust/example2 --csv-full-history
  
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile2.py --worker --master-host master --csv=example2